package service;

import dao.UserDAO;
import model.User;
import util.PasswordUtil;

public class AuthenticationService {

    private UserDAO userDAO;
    private dao.ActivityLogDAO activityLogDAO;
    private command.CommandManager commandManager;

    public AuthenticationService() {
        this.userDAO = new UserDAO();
        this.activityLogDAO = new dao.ActivityLogDAO();
        this.commandManager = command.CommandManager.getInstance();
    }

    public User login(String username, String password) {
        User user = userDAO.getUserByUsername(username);

        if (user != null) {
            String inputHash = PasswordUtil.hashPassword(password);
            if (inputHash.equals(user.getPasswordHash())) {
                activityLogDAO.logAction(user.getId(), "LOGIN", "User logged in successfully.");
                return user;
            }
        }
        return null;
    }

    public int changePassword(User user, String oldPassword, String newPassword) {
        String oldHash = PasswordUtil.hashPassword(oldPassword);
        if (!oldHash.equals(user.getPasswordHash())) {
            return 1; // Wrong old password
        }

        if (oldPassword.equals(newPassword)) {
            return 2; // Same as old password
        }

        String newHash = PasswordUtil.hashPassword(newPassword);
        boolean success = userDAO.updatePassword(user.getId(), newHash);
        return success ? 0 : 3; // 0=Success, 3=DB Error
    }

    public boolean isUserExists(String username) {
        return userDAO.getUserByUsername(username) != null;
    }

    public boolean registerUser(User currentUser, String username, String password, String firstName, String lastName,
            model.Role role) {
        if (isUserExists(username)) {
            return false;
        }

        String passwordHash = PasswordUtil.hashPassword(password);
        User newUser;

        // ID will be auto-generated by DB, so we pass 0 or handled by DAO if we change
        // User constructor to not require ID for new objects.
        // However, User constructor requires ID. Let's pass 0 for now, assuming DB
        // auto-increments.
        // Ideally we should have a constructor without ID or a builder, but sticking to
        // existing pattern:
        int tempId = 0;

        switch (role) {
            case TESTER:
                newUser = new model.Tester(tempId, username, firstName, lastName, passwordHash);
                break;
            case JUNIOR_DEVELOPER:
                newUser = new model.JuniorDeveloper(tempId, username, firstName, lastName, passwordHash);
                break;
            case SENIOR_DEVELOPER:
                newUser = new model.SeniorDeveloper(tempId, username, firstName, lastName, passwordHash);
                break;
            case MANAGER: // Should not happen based on requirements but good to have
                newUser = new model.Manager(tempId, username, firstName, lastName, passwordHash);
                break;
            default:
                return false;
        }

        commandManager.executeCommand(
                new command.AddUserCommand(userDAO, activityLogDAO, newUser, passwordHash, currentUser.getId()));
        return true;
    }

    public java.util.List<User> getAllUsers() {
        return userDAO.getAllUsers();
    }

    public boolean updateUser(User currentUser, User userToUpdate) {
        if (userDAO.updateUser(userToUpdate)) {
            activityLogDAO.logAction(currentUser.getId(), "UPDATE_USER",
                    "Updated user: " + userToUpdate.getUsername() + " (ID: " + userToUpdate.getId() + ")");
            return true;
        }
        return false;
    }

    public boolean deleteUser(User currentUser, int userId) {
        commandManager.executeCommand(
                new command.DeleteUserCommand(userDAO, activityLogDAO, userId, currentUser.getId()));
        return true;
    }

    public void undoLastAction() {
        commandManager.undo();
    }
}
